#pragma once

#include "hft/core/types.hpp"

#include <string>

namespace hft {

struct OrderRequest {
    std::string symbol;
    Side side{Side::Buy};
    OrderType type{OrderType::Limit};
    Price price{0};
    Quantity quantity{0};
};

// Order is the local source of truth for an order after the OMS accepts a client
// request. It intentionally stores only normalized state; exchange-specific IDs,
// session sequence numbers, and raw rejects should live in gateway-specific
// structures and be linked back to this ID.
struct Order {
    OrderId id{0};
    std::string symbol;
    Side side{Side::Buy};
    OrderType type{OrderType::Limit};
    Price price{0};
    Quantity quantity{0};
    Quantity filled{0};
    OrderStatus status{OrderStatus::New};
};

// Fill is generated by the simulated exchange today and by live execution
// gateways later. The OMS consumes this structure to update order state and
// realized position in risk.
struct Fill {
    OrderId order_id{0};
    std::string symbol;
    Side side{Side::Buy};
    Price price{0};
    Quantity quantity{0};
    TimestampNs ts_ns{0};
};

} // namespace hft
